### ISSUE TITLE
Update landing screenshots

### ISSUE THREAD

**Issue by aliceandbob-io** [aliceandbob-io/aliceandbob#35]
The 3 screenshots of the landing page need to be updated so that they match the feature recently added (different encryption options).

The 3 new screenshots may be found [here](https://github.com/aliceandbob-io/files) and are named ```features_xxx_v2```.

**Comment by megatank58** [comment]
Hello i would like to do this

**Comment by aliceandbob-io** [comment]
Thanks @Megatank58! I've just assigned you the issue! 🚀

**Comment by megatank58** [comment]
#36 adds the images and fixes this
