### ISSUE TITLE
docs: update of the landing page 

### ISSUE THREAD

**Issue by aliceandbob-io** [aliceandbob-io/aliceandbob#39]
The screenshot that appears in the ```/app/views/pages/_section_webapp.html.erb``` page needs to be replaced.
The new screenshot may be found [here](https://github.com/aliceandbob-io/files) and is named ```screenshot-online-pgp-tool_v2.png```.

**Comment by shivani1120** [comment]
Can I work on this issue?

**Comment by aliceandbob-io** [comment]
Sure! I assign it to you 👍

**Comment by shivani1120** [comment]
I am not able to push the changes in the remote repo . It shows an error  after writing the command git push -u origin shivani.
shivani is new branch that I created.

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by shivani1120** [comment]
@aliceandbob.io Could you suggest me something to get rid of this error

**Comment by aliceandbob-io** [comment]
My guess is that you have an issue with your SSH authentication on your forked repo, most probably because of the key you use. Try maybe authenticate with HTTPS instead of git@github.com.

**Comment by aliceandbob-io** [comment]
You may find useful links over [here](https://docs.github.com/en/authentication)

**Comment by shivani1120** [comment]
Thanks. I made my first contribution.

**Comment by aliceandbob-io** [comment]
Thanks @shivani1120! I proposed some changes to commit to your PR 👍
