### ISSUE TITLE
Need an apple touch icon

### ISSUE THREAD

**Issue by Kibranoz** [aliceandbob-io/aliceandbob#48]
On iPhone and iPad, we can add a shortcut to your website and make it full screen and like an app (PWA) but there is no apple touch icon so the icon is not a logo but a window on your website and it's not really beautiful. 

Adding an apple touch icon will make it an app like experience on iPad.

**Comment by aliceandbob-io** [comment]
Thanks @Kibranoz, I'll try to do it asap!

**Comment by aliceandbob-io** [comment]
The icon should now be live @Kibranoz, let me kow if it all works well!

**Comment by Kibranoz** [comment]
It works
