### ISSUE TITLE
[FRONTEND] Implement the ability to sign up

### ISSUE THREAD

**Issue by aliceandbob-io** [aliceandbob-io/aliceandbob#6]
#### Specs
Should have an icon link in the header which redirect to the signin/signup page

**Comment by Croustys** [comment]
I could try helping you out with that!

**Comment by aliceandbob-io** [comment]
Thanks for your help @croustys! Someone is already taking care of it though 👍

**Comment by shreyas098** [comment]
Can you please help with the sign in icon and poistion of it

**Comment by aliceandbob-io** [comment]
Hey @shreyas098! Thanks for your help! I'm sorry, but someone is already taking care of this issue

**Comment by shreyas098** [comment]
No problem . If there is anything else i can help do let me know @aliceandbob-io

**Comment by aliceandbob-io** [comment]
Sure! Thanks 👍
